config/routes.rb
Rails.application.routes.draw do
  get 'reporting/attendances'

  get 'reporting/statistics'
  get 'reporting/interim'
  get 'reporting/interim_pdf'
  get 'reporting/invoices'

  resources :attendances
  resources :energies
  get 'lln_imports/index'

  get 'lln_imports/import'

  resources :invoices do
    member do
      get 'show_detail'
      get 'show_surfaces'
      get 'show_surfaces_bis'
      get 'lln_detail_bis'
      get 'lln_detail_ter'
      get 'lln_detail_quater'
    end
  end
  resources :prices
  resources :parcels
  resources :sorting_details
  resources :sortings
  resources :washes
  resources :return_details
  resources :return_boxes
  resources :deliveries
  resources :offer_articles
  resources :offer_boxes
  resources :offers
  resources :negociated_prices
  resources :boxdetails
  resources :boxes
  resources :articles
  resources :events
  root to: 'visitors#index'
  devise_for :users
  resources :users

  resources :lln_imports do
    collection {post :import}
  end

  
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController


  def index
    @users = User.all
    @staff = User.staff.order('name ASC')
    @events = Event.all.order('event_start_date ASC')
    @user = current_user
    @articles = Article.all
    @rekwup_cups = @articles.where(:rekwup_cup => true)
    @attendances = Attendance.all
    @new_attendance = Attendance.new
  end
  

end

app/views/visitors/_attendance_form.html.erb
<ul class="list-group">
	<li class= "list-group-item list-group-item-warning text-center">

			<h4><strong>
				Cliquez sur votre nom pour pointer
			</strong></style></h4>

	</li>
</ul>




<% @staff.each do |user| %>

        <!-- Large modal -->
        <button type="button" class="btn btn-lg btn-default btn-block" data-toggle="modal" data-target="#user_attendance_<%= user.id %>">

          <%= user.full_name %>


        </button>

        <div class="modal fade" id="user_attendance_<%= user.id %>" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
          <div class="modal-dialog modal-lg">
            <div class="modal-content">

									<div class="text-center">
										<h2><%= Date.today.strftime("%d/%m/%Y") %></h2>

										<h3>Bonjour <%= user.full_name %>!</h3>

									</div>

                <div class="modal-header">

                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                  </button>

                    <h4 class="modal-title" id="myModalLabel">
                  
                     
                    </h4>
                </div>

                <div class="modal-body">

									<div class="text-center">



									<% if user.attendances.any? %>

										<% if @attendances.where(:user_id => user.id).last.start_time.present? && @attendances.where(:user_id => user.id).last.end_time.blank? %>

											<h4><%= t("attendance.now_in") %></h4>

											<h3><%= t("attendance.last_in") %><%= @attendances.where(:user_id => user.id).last.start_time.strftime("%d/%m/%Y") if @attendances.where(:user_id => user.id).last.start_time.present? %><br>

											<%= t("word.at") %><%= @attendances.where(:user_id => user.id).last.start_time.strftime("%H:%M") if @attendances.where(:user_id => user.id).last.start_time.present? %></h3>


											<%= simple_form_for(@attendances.where(:user_id => user.id).last) do |f| %>
											  <%= f.error_notification %>

											    <%= f.hidden_field :end_time, :value => Time.zone.now %>

											    <%= f.submit t("attendance.out"), class: "btn btn-warning btn-lg btn-block" %>

											<% end %>

										<% elsif @attendances.where(:user_id => user.id).last.start_time.present? && @attendances.where(:user_id => user.id).last.end_time.present? %>

											<h4><%= t("attendance.now_out") %></h4>

											<h3><%= t("attendance.last_out") %><%= @attendances.where(:user_id => user.id).last.end_time.strftime("%d/%m/%Y") if @attendances.where(:user_id => user.id).last.end_time.present? %><br>
											<%= t("word.at") %><%= @attendances.where(:user_id => user.id).last.end_time.strftime("%H:%M") if @attendances.where(:user_id => user.id).last.end_time.present? %></h3>



											<%= simple_form_for(@new_attendance) do |f| %>
											  <%= f.error_notification %>

											    <%= f.hidden_field :start_time, :value => Time.zone.now %>
											    <%= f.hidden_field :user_id, :value => user.id %>

											    <%= f.submit t("attendance.in"), class: "btn btn-info btn-lg btn-block" %>

											    <% end %>

										<% end %>

									<% else %>

											<h4><%= t("attendance.now_out") %></h4>


										<%= simple_form_for(@new_attendance) do |f| %>
										  <%= f.error_notification %>

										    <%= f.hidden_field :start_time, :value => Time.zone.now %>
										    <%= f.hidden_field :user_id, :value => user.id %>

										    <%= f.submit t("attendance.in"), class: "btn btn-info btn-lg btn-block" %>

										<% end %>

									<% end %>

									</div>
								</div>
							</div>
						</div>
					</div>

<% end %>

app/views/visitors/_index_admin.html.erb
<ul class="list-group">

  <li class="list-group-item list-group-item-warning">
		<strong>Evenements après aujourd'hui</strong>
	</li>

	<% @events.where("event_start_date > ?", Date.today).each do |event| %>

  <li class="list-group-item">
  	<div class="row">
  		<div class="col-md-4">
  			<%= link_to event.event_name, event_path(event), class: "btn btn-default btn-block" %>
  		</div>
  		<div class="col-md-2">
  			<%= event.event_start_date.strftime("%d/%m/%Y") %>
  		</div>
  		<div class="col-md-2">
  			<%= link_to event.organizer.full_name, user_path(event.organizer), class: "btn btn-default btn-block" %>
  			<%=  %>
  		</div>
  		<div class="col-md-2">

  		</div>

  	</div>
		
	</li>

	<% end %>


</ul>

  

app/views/visitors/_index_client.html.erb
    <% if current_user.name.present? %>

        <div class="jumbotron">
          <h2 class="text-center">Prêt de gobelets réutilisables</h2>


          <p>
            Nous vous livrons suffisamment de gobelets propres pour votre événement, nous les reprenons sales en fin d'événement. Vous ne vous occupez que de gérer les cautions, vous ne payez que le transport et le lavage.
            Vous pouvez déjà disposer de nos gobelets à partir d’une commande minimale de 500 gobelets ;  il n'y a pas de limite maximale, nous sommes capables de fournir les plus grands événements d'Europe.</p>
            <p>
            Créez votre événement pour obtenir une offre de prix
          </p>
      

            <%= link_to new_event_path do %>
              <%= content_tag(:i, t("event.new_event"), class: "fa fa-plus-circle btn btn-lg btn-block btn-info") %> 
            <% end %>
        </div>






    <% else %>

        <div class="jumbotron">
          <h2 class="text-center">Prêt de gobelets réutilisables</h2>


          <p>
            Nous vous livrons suffisamment de gobelets propres pour votre événement, nous les reprenons sales en fin d'événement. Vous ne vous occupez que de gérer les cautions, vous ne payez que le transport et le lavage.
            Vous pouvez déjà disposer de nos gobelets à partir d’une commande minimale de 500 gobelets ;  il n'y a pas de limite maximale, nous sommes capables de fournir les plus grands événements d'Europe.</p>
            <p>
            Complétez votre profil et créez votre événement pour obtenir une offre de service.

          </p>

          <%= link_to edit_user_path(@user) do %>
            <%= content_tag(:i, t("user.fill_profile"), class: "fa fa-plus-circle btn btn-lg btn-block btn-info") %> 
          <% end %>

        </div>



    <% end %>

app/views/visitors/_index_no_name.html.erb
        <div class="jumbotron">
          <h2 class="text-center">Prêt de gobelets réutilisables</h2>


          <p>
            Nous vous livrons suffisamment de gobelets propres pour votre événement, nous les reprenons sales en fin d'événement. Vous ne vous occupez que de gérer les cautions, vous ne payez que le transport et le lavage.
            Vous pouvez déjà disposer de nos gobelets à partir d’une commande minimale de 500 gobelets ;  il n'y a pas de limite maximale, nous sommes capables de fournir les plus grands événements d'Europe.</p>
            <p>
            Complétez votre profil et créez votre événement pour obtenir une offre de service.

          </p>

          <%= link_to edit_user_path(@user) do %>
            <%= content_tag(:i, t("user.fill_profile"), class: "fa fa-plus-circle btn btn-lg btn-block btn-info") %> 
          <% end %>

        </div>

app/views/visitors/_not_signed_in.html.erb
<div class="jumbotron text-justify">
  <h2 class="text-center">
  	Prêt de gobelets réutilisables
  </h2>


  <p>
    Nous vous livrons suffisamment de gobelets propres pour votre événement, nous les reprenons sales en fin d'événement. Vous ne vous occupez que de gérer les cautions, vous ne payez que le transport et le lavage.
    Vous pouvez déjà disposer de nos gobelets à partir d’une commande minimale de 500 gobelets ;  il n'y a pas de limite maximale, nous sommes capables de fournir les plus grands événements d'Europe.</p>
    <p>
    Enregistrez-vous et créez votre événement pour obtenir une offre de service.
  </p>

    <%= link_to new_user_registration_path do %>
      <%= content_tag(:i, t("menu.sign_up"), class: "fa fa-plus-circle btn btn-lg btn-block btn-info") %> 
    <% end %>

app/views/visitors/index.html.erb
  <% if user_signed_in? %>

    <% if current_user.name.blank? %>

      <%= render 'index_no_name' %>    

    <% end %>


    <% if current_user.leader %>

      <%= render 'attendance_form' %>

    <% end %>

    <% if current_user.client %>

      <%= render 'index_client' %>

    <% end %>

    <% if current_user.admin %>

      <%= render 'index_admin' %>

    <% end %>


  <% else %>

    <%= render 'not_signed_in' %>
          
  <% end %>

 