config/routes.rb
Rails.application.routes.draw do
  get 'reporting/attendances'

  get 'reporting/statistics'
  get 'reporting/interim'
  get 'reporting/interim_pdf'
  get 'reporting/invoices'

  resources :attendances
  resources :energies
  get 'lln_imports/index'

  get 'lln_imports/import'

  resources :invoices do
    member do
      get 'show_detail'
      get 'show_surfaces'
      get 'show_surfaces_bis'
      get 'lln_detail_bis'
      get 'lln_detail_ter'
      get 'lln_detail_quater'
    end
  end
  resources :prices
  resources :parcels
  resources :sorting_details
  resources :sortings
  resources :washes
  resources :return_details
  resources :return_boxes
  resources :deliveries
  resources :offer_articles
  resources :offer_boxes
  resources :offers
  resources :negociated_prices
  resources :boxdetails
  resources :boxes
  resources :articles
  resources :events
  root to: 'visitors#index'
  devise_for :users
  resources :users

  resources :lln_imports do
    collection {post :import}
  end

  
end

app/models/article.rb
class Article < ActiveRecord::Base
	
	has_many :boxdetails
	has_many :boxes, through: :boxdetails

	has_many :prices
	has_many :offer_articles
	has_many :sorting_details

	scope :not_washable, lambda {where.not(:is_washable => true)}
	scope :washable, lambda {where(:is_washable => true)}
	scope :is_cup, lambda {where(:is_cup => true)}
	scope :is_rekwup, lambda {where(:rekwup_cup => true)}
	scope :is_lln, lambda {where(:is_lln => true)}
	scope :is_bep, lambda {where(:is_bep => true)}
	scope :is_patro, lambda {where(:is_patro => true)}
	scope :is_twenty, lambda {where(:is_twenty => true)}
	scope :is_twentyfive, lambda {where(:is_twentyfive => true)}
	scope :is_forty, lambda {where(:is_forty => true)}
	scope :is_fifty, lambda {where(:is_fifty => true)}
	scope :is_litre, lambda {where(:is_litre => true)}
	scope :is_cc, lambda {where(:is_cc => true)}
	scope :is_ep, lambda {where(:is_ep => true)}
	scope :is_eco, lambda {where(:is_eco => true)}
	scope :is_wine, lambda {where(:is_wine => true)}
	scope :is_cava, lambda {where(:is_cava => true)}
	scope :is_shot, lambda {where(:is_shot => true)}
	scope :is_transport, lambda {where(:transport => true)}
	scope :is_big_box, lambda {where(:is_big_box => true)}
	scope :is_small_box, lambda {where(:is_small_box => true)}
	scope :is_top, lambda {where(:is_top => true)}
	scope :is_palette, lambda {where(:is_palette => true)}
	scope :is_empty, lambda {where(:is_empty => true)}
	scope :is_corona, lambda {where(:is_corona => true)}

	def total_february
		total_february = 0
		Sorting.february.each do |sorting|
			total_february += sorting.total_sorting(self)
		end
		total_february
	end

	def total_march
		total_march = 0
		Sorting.march.each do |sorting|
			total_march += sorting.total_sorting(self)
		end
		total_march
	end

	def total_april
		total_april = 0
		Sorting.april.each do |sorting|
			total_april += sorting.total_sorting(self)
		end
		total_april
	end

	def total_may
		total_may = 0
		Sorting.may.each do |sorting|
			total_may += sorting.total_sorting(self)
		end
		total_may
	end

	def total_june
		total_june = 0
		Sorting.june.each do |sorting|
			total_june += sorting.total_sorting(self)
		end
		total_june
	end

	def total_july
		total_july = 0
		Sorting.july.each do |sorting|
			total_july += sorting.total_sorting(self)
		end
		total_july
	end
	def full_name
		"#{article_name}"
	end

	def cup_type
		if is_cc
			I18n.t("article.is_cc")
		elsif is_ep
			I18n.t("article.is_ep")
		elsif is_eco
			I18n.t("article.is_eco")
		elsif is_wine
			I18n.t("article.is_wine")
		elsif is_cava
			I18n.t("article.is_cava")
		elsif is_shot
			I18n.t("article.is_shot")
		elsif is_big_box
			I18n.t("article.is_big_box")
		elsif is_small_box
			I18n.t("article.is_small_box")
		elsif is_top
			I18n.t("article.is_top")
		elsif is_palette
			I18n.t("article.is_palette")
		elsif transport
			I18n.t("article.transport")
		end	
	end

	def cup_content
		if is_twenty
			I18n.t("article.is_twenty")
		elsif is_twentyfive
			I18n.t("article.is_twentyfive")
		elsif is_forty
			I18n.t("article.is_forty")
		elsif is_fifty
			I18n.t("article.is_fifty")
		elsif is_litre
			I18n.t("article.is_litre")
		end
	end

	def cup_owner
		if rekwup_cup
			I18n.t("article.rekwup_cup")
		elsif is_lln
			I18n.t("article.is_lln")
		elsif is_patro
			I18n.t("article.is_patro")
		elsif is_bep
			I18n.t("article.is_bep")
		end			
	end


	def box_value
		if quantity_bigbox.present?
			quantity_bigbox
		else
			0
		end		
	end

	def pile_value
		if quantity_pile.present?
			quantity_pile
		else
			0
		end
	end

	def has_price
		if self.prices.any?
			"#{self.prices.count} Prix"
		end
	end

	def right_wash_price(user)
		if user.negociated_price == true
			if Price.negociated.where(:article_id => id).where(:user_id => user.id).any?
				Price.negociated.where(:article_id => id).where(:user_id => user.id).last.washing_value
			else
				if Price.regular.where(:article_id => id).any?
					Price.regular.where(:article_id => id).last.washing_value
				else
					0
				end
			end
		else
			if Price.regular.where(:article_id => id).any?
				Price.regular.where(:article_id => id).last.washing_value
			else
				0
			end
		end

	end

	def right_washing_small_price(user)
		if user.negociated_price == true
			if Price.negociated.where(:article_id => id).where(:user_id => user.id).any?
				Price.negociated.where(:article_id => id).where(:user_id => user.id).last.washing_small_value
			else
				if Price.regular.where(:article_id => id).any?
					Price.regular.where(:article_id => id).last.washing_small_value
				else
					0
				end
			end
		else
			if Price.regular.where(:article_id => id).any?
				Price.regular.where(:article_id => id).last.washing_small_value
			else
				0
			end
		end

	end

	def right_handwash_price(user)
		if user.negociated_price == true
			if Price.negociated.where(:article_id => id).where(:user_id => user.id).any?
				Price.negociated.where(:article_id => id).where(:user_id => user.id).last.handwash_value
			else
				if Price.regular.where(:article_id => id).any?
					Price.regular.where(:article_id => id).last.handwash_value
				else
					0
				end
			end
		else
			if Price.regular.where(:article_id => id).any?
				Price.regular.where(:article_id => id).last.handwash_value
			else
				0
			end
		end
	end

	def right_handling_price(user)
		if user.negociated_price == true
			if Price.negociated.where(:article_id => id).where(:user_id => user.id).any?
				Price.negociated.where(:article_id => id).where(:user_id => user.id).last.handling_value
			else
				if Price.regular.where(:article_id => id).any?
					Price.regular.where(:article_id => id).last.handling_value
				else
					0
				end
			end
		else
			if Price.regular.where(:article_id => id).any?
				Price.regular.where(:article_id => id).last.handling_value
			else
				0
			end
		end
	end

	def right_deposit_price(user, event)
		if event.deposit_on_site.present?
			if event.deposit_on_site = 1
				if Price.regular.where(:article_id => id).any?
					Price.regular.where(:article_id => id).last.deposit_value
				else
					0.7
				end
			elsif event.deposit_on_site = 0
				if Price.regular.where(:article_id => id).any?
					Price.regular.where(:article_id => id).last.deposit_value
				else
					0
				end
			elsif event.deposit_on_site >= 1.0005
				event.deposit_on_site * 0.7
			else
				0
			end
		else
			if user.negociated_price == true
				if Price.negociated.where(:article_id => id).where(:user_id => user.id).any?
					Price.negociated.where(:article_id => id).where(:user_id => user.id).last.deposit_value
				else
					if Price.regular.where(:article_id => id).any?
						Price.regular.where(:article_id => id).last.deposit_value
					else
						0
					end
				end
			else
				if Price.regular.where(:article_id => id).any?
					Price.regular.where(:article_id => id).last.deposit_value
				else
					0
				end
			end
		end
	end

	def right_sell_price(user)
		if user.negociated_price == true
			if Price.negociated.where(:article_id => id).where(:user_id => user.id).any?
				Price.negociated.where(:article_id => id).where(:user_id => user.id).last.sell_value
			else
				if Price.regular.where(:article_id => id).any?
					Price.regular.where(:article_id => id).last.sell_value
				else
					0
				end
			end
		else
			if Price.regular.where(:article_id => id).any?
				Price.regular.where(:article_id => id).last.sell_value
			else
				0
			end
		end
	end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all.order('article_name ASC')
    @user = current_user
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])
    @user = current_user
    @new_price = Price.new
    @prices = Price.all
    @regular_prices = @prices.where(:regular => true)
    @myregular_price = @regular_prices.where(:article_id => @article.id).last
  end

  # GET /articles/new
  def new
    @article = Article.new
    @user = current_user
    unless current_user.admin
      redirect_to :back, :alert => t("notice.access")
    end
  end

  # GET /articles/1/edit
  def edit
    @user = current_user
    unless current_user.admin
      redirect_to :back, :alert => t("notice.access")
    end
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: t("notice.article_created") }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: t("notice.article_updated") }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: t("notice.article_destroyed") }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:is_other, :transport, :article_name, :article_content, :article_type, :article_category, :quantity_bigbox, :quantity_smallbox, :quantity_pile, :is_washable, :rekwup_cup, :weight, :is_cup, :is_lln, :is_patro, :is_bep, :is_cc, :is_ep, :is_eco, :is_wine, :is_cava, :is_shot, :is_big_box, :is_small_box, :is_top, :is_palette, :is_twenty, :is_twentyfive, :is_forty, :is_fifty, :is_litre, :age, :pile_smallbox, :champagne)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
    <ul class="list-group">

      <%= simple_form_for(@article) do |f| %>
        <%= f.error_notification %>


        <li class="list-group-item list-group-item-warning">
          <h4><strong><%= t("article.edit_article") %></strong></h4>
        </li>
        <li class="list-group-item">
          <div class="row")>
            <div class="col-md-4">
              <strong>
                <%= f.input :article_name %>
              </strong>
            </div>

            <div class="col-md-8">
              <div class="col-md-2">
                <br><%= f.input :is_washable %>
              </div>
              <div class="col-md-2">
                <br><%= f.input :is_cup %>
              </div>
              <div class="col-md-2">
                <br><%= f.input :is_big_box %>
              </div>
              <div class="col-md-2">
                <br><%= f.input :is_small_box %>
              </div>
              <div class="col-md-2">
                <br><%= f.input :is_top %>
              </div>
              <div class="col-md-2">
                <br><%= f.input :is_palette %>
              </div>

            </div>
          </div>
        </li>


       <li class="list-group-item">
          <div class="row")>
            <div class="col-md-1">
                <%= f.input :is_cc %>
            </div>

            <div class="col-md-1">
              <%= f.input :is_ep %>
            </div>

            <div class="col-md-1">
              <%= f.input :is_eco %>
            </div>

            <div class="col-md-1">
              <%= f.input :is_wine %>
            </div>

            <div class="col-md-1">
              <%= f.input :is_cava %>
            </div>

            <div class="col-md-1">
              <%= f.input :champagne %>
            </div>

            <div class="col-md-1">
              <%= f.input :is_shot %>
            </div>

            <div class="col-md-1">
              <%= f.input :is_other %>
            </div>
          </div>
        </li>

       <li class="list-group-item">
          <div class="row")>
            <div class="col-md-2">
                <%= f.input :is_twenty %>
            </div>

            <div class="col-md-2">
              <%= f.input :is_twentyfive %>
            </div>

            <div class="col-md-2">
              <%= f.input :is_forty %>
            </div>

            <div class="col-md-2">
              <%= f.input :is_fifty %>
            </div>

            <div class="col-md-2">
              <%= f.input :is_litre %>
            </div>

            <div class="col-md-2">
             
            </div>

          </div>
        </li>

       <li class="list-group-item">
          <div class="row")>
            <div class="col-md-2">
                <%= f.input :rekwup_cup %>
            </div>

            <div class="col-md-2">
              <%= f.input :is_lln %>
            </div>

            <div class="col-md-2">
              <%= f.input :is_bep %>
            </div>

            <div class="col-md-2">
              <%= f.input :is_patro %>
            </div>

            <div class="col-md-2">
              <%= f.input :age %>   
            </div>
          </div>
        </li>


        <li class="list-group-item">
          <div class="row text-center")>

            <div class="col-md-2">
              <%= f.input :article_content %>
            </div>

            <div class="col-md-2">
              <%= f.input :quantity_bigbox %>
            </div>

            <div class="col-md-2">
              <%= f.input :quantity_smallbox %>
            </div>

            <div class="col-md-2">
              <%= f.input :quantity_pile %>
            </div>

            <div class="col-md-2">
              <%= f.input :pile_smallbox %>
            </div>

            <div class="col-md-2">
                <%= f.input :weight %>
            </div>            
          </div>
        </li>

        <li class="list-group-item">
          <div class="row text-center")>

            <div class="col-md-2">
              <%= f.input :transport %>
            </div>

            <div class="col-md-2">
           
            </div>

            <div class="col-md-2">
              
            </div>

            <div class="col-md-2">
             
            </div>

            <div class="col-md-2">
              
            </div>            
          </div>
        </li>
          <div class="row more-padding">

            <div class="col-md-6">
              <%= link_to t("menu.back"), articles_path, class: "btn btn-lg btn-block btn-default" %>
            </div>
            <div class="col-md-6">
              <% if @user.admin %>
                <%= f.button :submit, class: "btn btn-info btn-lg btn-block" %>
              <% end %>
            </div>

          </div>

      
      <% end %>
    </ul>



    
  </div>

app/views/articles/edit.html.erb
<%= render 'form' %>

app/views/articles/index.html.erb
  <% if @user.client %>

    <h4>Cette page est en construction.</h4>

  <% else %>

    <% if @user.admin %>
      <%= link_to t("article.new_article"), new_article_path, class: "btn btn-block btn-info" %><br>
    <% end %>



    <ul class="list-group">
      <li class="list-group-item list-group-item-warning">
        <h4><strong>
          <%= t("article.listing_articles") %>
        </strong></h4>
      </li>

      <li class="list-group-item">
        <div class="row">
          <strong>
            <div class="col-xs-6 col-md-4">
              <%= t("article.article_name") %>
            </div>

            <div class="col-xs-6 col-md-2">
              <%= t("article.article_type") %>
            </div>

            <div class="col-xs-6 col-md-2">
              <%= t("article.article_content") %>
            </div>

            <div class="col-xs-6 col-md-2">
              <%= t("article.brand") %>
            </div>

            <div class="col-xs-6 col-md-2">
              <%= t("menu.prices") %>
            </div>
          </strong>
        </div>
      </li>

        <% @articles.each do |article| %>
        
          <li class="list-group-item">
            <div class="row">

              <div class="col-xs-6 col-md-4">
                <%= article.id %> - <%= article.full_name %>

                  <%= link_to edit_article_path(article) do %>
                    <%= content_tag(:i, "", class: "fa fa-pencil-square-o") %>
                  <% end %>

                  <%= link_to article_path(article) do %>
                    <%= content_tag(:i, "", class: "fa fa-eye") %>
                  <% end %>
              </div>

              <div class="col-xs-6 col-md-2">
                <%= article.cup_type %>
              </div>

              <div class="col-xs-6 col-md-2">
                <%= article.cup_content %>
              </div>

              <div class="col-xs-6 col-md-2">
                <%= article.cup_owner %>
              </div>

              <div class="col-xs-6 col-md-2">
                <%= article.has_price %>
              </div>
            </div>
          </li>
        <% end %>
  <% end %>

app/views/articles/new.html.erb
<h2><%= t("article.new_article") %></h2>

<%= render 'form' %>

app/views/articles/show.html.erb
<% if @user.client %>

<h4>Cette page est en construction.</h4>

<% else %>


    <ul class="list-group">
      
        <li class="list-group-item list-group-item-warning">
          <div class="row">
            <div class="col-md-3">
              <b>
                <%= @article.id %> - <%= @article.full_name %>
              </b>
            </div>

            <div class="col-md-9">

              <div class="col-md-2">
                <% if @article.is_washable %>
                  <b>
                    <%= t("article.is_washable") %>
                  </b>
                <% end %>
              </div>

              <div class="col-md-2">
                <% if @article.is_cup %>
                  <b>
                    <%= t("article.is_cup") %>
                  </b>
                <% end %>
              </div>

              <div class="col-md-2">
                <% if @article.is_big_box %>
                  <b>
                    <%= t("article.is_big_box") %>
                  </b>
                <% end %>
              </div>

              <div class="col-md-2">
                <% if @article.is_small_box %>
                  <b>
                    <%= t("article.is_small_box") %>
                  </b>
                <% end %>
              </div>

              <div class="col-md-2">
                <% if @article.is_top %>
                  <b>
                    <%= t("article.is_top") %>
                  </b>
                <% end %>
              </div>

              <div class="col-md-2">
                <% if @article.is_palette %>
                  <b>
                    <%= t("article.is_palette") %>
                  </b>
                <% end %>
              </div>
            </div>
          </div>
        </li>

        <li class="list-group-item list-group-item-warning">
          <b><%= t("article.article_type") %></b>
        </li>


        <li class="list-group-item">
          <div class="row text-center")>
            <div class="col-md-1">
              <% if @article.is_cc %>
                <b>
                  <%= t("article.is_cc") %>
                </b>
              <% end %>
            </div>

            <div class="col-md-1">
                <% if @article.is_ep %>
                  <b>
                    <%= t("article.is_ep") %>
                  </b>
                <% end %>
            </div>

            <div class="col-md-1">
                <% if @article.is_eco %>
                  <b>
                    <%= t("article.is_eco") %>
                  </b>
                <% end %>
            </div>

            <div class="col-md-1">
                <% if @article.is_wine %>
                  <b>
                    <%= t("article.is_wine") %>
                  </b>
                <% end %>
            </div>
            <div class="col-md-1">
                <% if @article.is_cava %>
                  <b>
                    <%= t("article.is_cava") %>
                  </b>
                <% end %>
            </div>  

            <div class="col-md-1">
                <% if @article.champagne %>
                  <b>
                    <%= t("article.is_champagne") %>
                  </b>
                <% end %>
            </div>  

            <div class="col-md-1">
                <% if @article.is_shot %>
                  <b>
                    <%= t("article.is_shot") %>
                  </b>
                <% end %>
            </div>

            <div class="col-md-1">
                <% if @article.is_other %>
                  <b>
                    <%= t("article.is_other") %>
                  </b>
                <% end %>
            </div>             
          </div>
        </li>

        <li class="list-group-item list-group-item-warning">
          <b><%= t("article.article_content") %></b>
        </li>

        <li class="list-group-item">
          <div class="row text-center")>
            <div class="col-md-2">
              <% if @article.is_twenty %>
                <b>
                  <%= t("article.is_twenty") %>
                </b>
              <% end %>
            </div>

            <div class="col-md-2">
                <% if @article.is_twentyfive %>
                  <b>
                    <%= t("article.is_twentyfive") %>
                  </b>
                <% end %>
            </div>

            <div class="col-md-2">
                <% if @article.is_forty %>
                  <b>
                    <%= t("article.is_forty") %>
                  </b>
                <% end %>
            </div>

            <div class="col-md-2">
                <% if @article.is_fifty %>
                  <b>
                    <%= t("article.is_fifty") %>
                  </b>
                <% end %>
            </div>
            <div class="col-md-2">
                <% if @article.is_litre %>
                  <b>
                    <%= t("article.is_litre") %>
                  </b>
                <% end %>
            </div>  

            <div class="col-md-2">

            </div>              
          </div>
        </li>

        <li class="list-group-item list-group-item-warning">
          <b><%= t("article.article_category") %></b>
        </li>


        <li class="list-group-item">
          <div class="row text-center")>
            <div class="col-md-2">
              <% if @article.rekwup_cup %>
                <b>
                  <%= t("article.rekwup_cup") %>
                </b>
              <% end %>
            </div>

            <div class="col-md-2">
                <% if @article.is_lln %>
                  <b>
                    <%= t("article.is_lln") %>
                  </b>
                <% end %>
            </div>

            <div class="col-md-2">
                <% if @article.is_bep %>
                  <b>
                    <%= t("article.is_bep") %>
                  </b>
                <% end %>
            </div>

            <div class="col-md-2">
                <% if @article.age %>
                  <b>
                    <%= t("article.is_age") %>
                  </b>
                <% end %>
            </div>

            <div class="col-md-2">
                <% if @article.is_patro %>
                  <b>
                    <%= t("article.is_patro") %>
                  </b>
                <% end %>
            </div>            
          </div>
        </li>

        <li class="list-group-item list-group-item-warning">
          <b><%= t("article.data") %></b>
        </li>

        <li class="list-group-item">
          <div class="row text-center")>
            <div class="col-md-2">
              <b>
                <%= t("article.article_content") %><br>
              </b>
              <%= @article.article_content %> CL
            </div>
            <div class="col-md-2">
              <b>
                <%= t("article.quantity_bigbox") %><br>
              </b>
              <%= @article.quantity_bigbox %>
            </div>

            <div class="col-md-2">
              <b>
                <%= t("article.quantity_smallbox") %><br>
              </b>
              <%= @article.quantity_smallbox %>
            </div>

            <div class="col-md-2">
              <b>
                <%= t("article.quantity_pile") %><br>
              </b>
              <%= @article.quantity_pile %>
            </div>

            <div class="col-md-2">
              <b>
                <%= t("article.pile_smallbox") %><br>
              </b>
              <%= @article.pile_smallbox %>
            </div>


            <div class="col-md-2">
              <b>
                <%= t("article.weight") %><br>
              </b>
                <%= @article.weight %> kg
            </div>            
          </div>
        </li>

        <li class="list-group-item list-group-item-warning">
          <b><%= t("article.other") %></b>
        </li>

        <li class="list-group-item">
          <div class="row text-center")>
            <div class="col-md-2">

              <% if @article.transport %>
                <b>
                  <%= t("article.transport") %>
                </b>
              <% end %>

            </div>
            
            <div class="col-md-3">

            </div>

            <div class="col-md-3">

            </div>

            <div class="col-md-2">

            </div>

            <div class="col-md-2">

            </div>            
          </div>
        </li>
      </ul>


    <div class="row more-padding">

      <div class="col-md-6">
        <%= link_to t("menu.back"), articles_path, class: "btn btn-lg btn-block btn-default" %>
      </div>
      <div class="col-md-6">
        <% if @user.admin %>
          <%= link_to t("menu.edit"), edit_article_path(@article), class: "btn btn-lg btn-block btn-info" %>
        <% end %>
      </div>
    </div>



    <ul class="list-group">

    <% if @myregular_price.present? %>

        <li class="list-group-item list-group-item-warning">
          <div class="row")>
            <div class="col-md-4">
              <b>


                  <% if @myregular_price.regular %>
                    <%= t("price.regular") %>
                  <% elsif @myregular_price.negociated %>
                    <%= t("price.negociated") %>
                  <% end %>


              </b>
            </div>

            <div class="col-md-4">
                  <b>
                    <%= t("price.valid_from") %> : <%= @myregular_price.valid_from.strftime("%d/%m/%Y") if @myregular_price.valid_from.present? %>
                  </b>
            </div>


            <div class="col-md-4">
                  <b>
                    <%= t("price.valid_till") %> : <%= @myregular_price.valid_till.strftime("%d/%m/%Y") if @myregular_price.valid_till.present? %>
                  </b>
            </div>

          </div>
        </li>



        <li class="list-group-item">
          <div class="row text-center")>
            <div class="col-md-2">
              <b>
                <%= t("article.washing_price") %><br>
              </b>
              <%= number_to_currency(@myregular_price.washing, :unit => '€', :precision => 4) if @myregular_price %>
            </div>

            <div class="col-md-2">
              <b>
                <%= t("article.washing_small") %><br>
              </b>
              <%= number_to_currency(@myregular_price.washing_small, :unit => '€', :precision => 4) if @myregular_price %>
            </div>

            <div class="col-md-2">
              <b>
                <%= t("article.handwash_price") %><br>
              </b>
              <%= number_to_currency(@myregular_price.handwash, :unit => '€', :precision => 4) if @myregular_price %>
            </div>

            <div class="col-md-2">
              <b>
                <%= t("article.tab_price") %><br>
              </b>
              <%= number_to_currency(@myregular_price.handling, :unit => '€', :precision => 4) if @myregular_price %>
            </div>

            <div class="col-md-2">
              <b>
                <%= t("article.deposit_price") %><br>
              </b>
              <%= number_to_currency(@myregular_price.deposit, :unit => '€', :precision => 4) if @myregular_price %>
            </div>

            <div class="col-md-2">
              <b>
                <%= t("article.sell_price") %><br>
              </b>
              <%= number_to_currency(@myregular_price.sell, :unit => '€', :precision => 4) if @myregular_price %>
            </div>
          </div>
        </li>

      <% end %>

    </ul>

    <% if current_user.admin %>

      <div class="row">

        <div class="col-md-6">
          <%= render 'add_prices' %>  
        </div>
        <div class="col-md-6">
          <%= render 'change_prices' %>       
        </div>
      </div>


    <% end %>


    
 




  
  <% end %>