config/routes.rb
Rails.application.routes.draw do
  get 'reporting/attendances'

  get 'reporting/statistics'
  get 'reporting/interim'
  get 'reporting/interim_pdf'
  get 'reporting/invoices'

  resources :attendances
  resources :energies
  get 'lln_imports/index'

  get 'lln_imports/import'

  resources :invoices do
    member do
      get 'show_detail'
      get 'show_surfaces'
      get 'show_surfaces_bis'
      get 'lln_detail_bis'
      get 'lln_detail_ter'
      get 'lln_detail_quater'
    end
  end
  resources :prices
  resources :parcels
  resources :sorting_details
  resources :sortings
  resources :washes
  resources :return_details
  resources :return_boxes
  resources :deliveries
  resources :offer_articles
  resources :offer_boxes
  resources :offers
  resources :negociated_prices
  resources :boxdetails
  resources :boxes
  resources :articles
  resources :events
  root to: 'visitors#index'
  devise_for :users
  resources :users

  resources :lln_imports do
    collection {post :import}
  end

  
end

app/models/box.rb
class Box < ActiveRecord::Base
	
  has_many :boxdetails
  has_many :articles, through: :boxdetails
  
  has_many :offer_boxes
  has_many :offers, through: :offer_boxes

  has_many :return_details

  has_many :parcels

  scope :closed, lambda {where(:box_is_full => true)}
  scope :is_empty, lambda {where(:is_empty => true)}
  scope :is_kpt, lambda {where(:is_kpt => true)}
  scope :is_rekwup, lambda {where(:is_rekwup => true)}
  scope :is_lln, lambda {where(:is_lln => true)}
  scope :is_bep, lambda {where(:is_bep => true)}
  scope :is_patro, lambda {where(:is_patro => true)}
  scope :is_twenty, lambda {where(:is_twenty => true)}
  scope :is_twentyfive, lambda {where(:is_twentyfive => true)}
  scope :is_forty, lambda {where(:is_forty => true)}
  scope :is_fifty, lambda {where(:is_fifty => true)}
  scope :is_litre, lambda {where(:is_litre => true)}
  scope :is_cc, lambda {where(:is_cc => true)}
  scope :is_ep, lambda {where(:is_ep => true)}
  scope :is_eco, lambda {where(:is_eco => true)}
  scope :is_wine, lambda {where(:is_wine => true)}
  scope :is_cava, lambda {where(:is_cava => true)}
  scope :is_shot, lambda {where(:is_shot => true)}
  scope :is_bigbox, lambda {where(:bigbox => true)}
  scope :is_smallbox, lambda {where(:smallbox => true)}
  scope :is_mixed, lambda {where(:mixed => true)}
  scope :is_regular, lambda {where(:box_regular => true)}
  scope :is_not_box, lambda {where(:bigbox => blank?, :smallbox => blank?)}
  scope :is_box, lambda {where(:bigbox => true, :smallbox => blank?) or where(:bigbox => blank?, :smallbox => true)}


	def automatic
      boxdetails.create(:box_id => id, :article_id => Article.is_top.first.id, :box_article_quantity => "1")
    if bigbox
      boxdetails.create(:box_id => id, :article_id => Article.is_big_box.first.id, :box_article_quantity => "1")
    elsif smallbox
      boxdetails.create(:box_id => id, :article_id => Article.is_small_box.first.id, :box_article_quantity => "1")
    end
	end

  def weight
    weight = 0
    self.boxdetails.find_each do |boxdetail|
    weight += boxdetail.weight
    end
    weight
  end

  def type
    if box_regular
      I18n.t("box.box_regular")
    elsif mixed
      I18n.t("box.mixed")
    elsif is_empty
      I18n.t("box.is_empty")
    end   
  end

  def size
    if bigbox
      I18n.t("box.bigbox")
    elsif smallbox
      I18n.t("box.smallbox")      
    end
  end

  def cup_type
    if is_cc
      I18n.t("article.is_cc")
    elsif is_ep
      I18n.t("article.is_ep")
    elsif is_eco
      I18n.t("article.is_eco")
    elsif is_wine
      I18n.t("article.is_wine")
    elsif is_cava
      I18n.t("article.is_cava")
    elsif is_shot
      I18n.t("article.is_shot")
    end
  end

  def cup_content
    if is_twenty
      I18n.t("article.is_twenty")
    elsif is_twentyfive
      I18n.t("article.is_twentyfive")
    elsif is_forty
      I18n.t("article.is_forty")
    elsif is_fifty
      I18n.t("article.is_fifty")
    elsif is_litre
      I18n.t("article.is_litre")
    end
  end

  def cup_owner
    if is_rekwup
      I18n.t("article.rekwup_cup")
    elsif is_lln
      I18n.t("article.is_lln")
    elsif is_patro
      I18n.t("article.is_patro")
    elsif is_bep
      I18n.t("article.is_bep")
    end     
  end

  def sent_boxes(offer)
    offer.sent_boxes(self)
  end

  def is_big_box
    bigbox == true   
  end

  def is_small_box
    smallbox == true    
  end

  def is_not_box
    if smallbox == blank? && bigbox == blank?
      true
    else
      false
    end  
  end
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  before_action :set_box, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /boxes
  # GET /boxes.json
  def index
    @boxes = Box.all.order('box_name ASC')
    @user = current_user
    @staff = @user.staff
    @admin = @user.admin
    @closed_boxes = @boxes.where(:box_is_full => true)
    @open_boxes = @boxes.where.not(:box_is_full => true)
    unless @admin or @staff
      redirect_to :root, :alert => t("notice.access")
    end
  end

  # GET /boxes/1
  # GET /boxes/1.json
  def show
    @user = current_user
    @staff = @user.staff
    @admin = @user.admin
    @box = Box.find(params[:id])
    @new_boxdetail = Boxdetail.new
    @boxdetails = Boxdetail.all
    @articles = Article.all
    @thisboxdetails = @boxdetails.where(:box_id => @box.id)
    unless @admin or @staff
      redirect_to :root, :alert => t("notice.access")
    end
  end

  # GET /boxes/new
  def new
    @box = Box.new
    @user = current_user
    @staff = @user.staff
    @admin = @user.admin
    unless @admin or @staff
      redirect_to :root, :alert => t("notice.access")
    end
  end

  # GET /boxes/1/edit
  def edit
    @user = current_user
    @staff = @user.staff
    @admin = @user.admin
    unless @admin or @staff
      redirect_to :root, :alert => t("notice.access")
    end
  end

  # POST /boxes
  # POST /boxes.json
  def create
    @box = Box.new(box_params)

    respond_to do |format|
      if @box.save
        @box.automatic       
        format.html { redirect_to @box, notice: t("notice.box_created") }
        format.json { render :show, status: :created, location: @box }
      else
        format.html { render :new }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boxes/1
  # PATCH/PUT /boxes/1.json
  def update
    respond_to do |format|
      if @box.update(box_params)
        format.html { redirect_to @box, notice: t("notice.box_updated") }
        format.json { render :show, status: :ok, location: @box }
      else
        format.html { render :edit }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boxes/1
  # DELETE /boxes/1.json
  def destroy
    @box.destroy
    respond_to do |format|
      format.html { redirect_to boxes_url, notice: t("notice.box_destroyed") }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_box
      @box = Box.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def box_params
      params.require(:box).permit(:box_name, :box_regular, :box_type, :bigbox, :smallbox, :box_is_full, :is_empty, :is_cc, :is_ep, :is_eco, :is_wine, :is_cava, :is_twenty, :is_twentyfive, :is_forty, :is_fifty, :is_litre, :is_lln, :is_rekwup, :is_bep, :is_patro, :is_corona, :is_shot, :mixed, :is_kpt, :is_age, :is_champagne)
    end
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/views/boxes/_form.html.erb
<ul class="list-group">

<%= simple_form_for(@box) do |f| %>
  <%= f.error_notification %>


        <li class="list-group-item list-group-item-warning">
          <h4><strong>
            <%= t("box.edit_box") %>
          </strong></h4>
        </li>

        <li class="list-group-item">  
          <div class="row")>

            <div class="col-md-3">
              <%= f.input :box_name %>
            </div>

            <div class="col-md-3">
              <%= f.input :bigbox %>
            </div>

            <div class="col-md-3">
              <%= f.input :smallbox %>
            </div>

            <div class="col-md-3">
              
            </div>

          </div>
        </li>


        <li class="list-group-item">
          <div class="row text-center">
            <div class="col-md-3">
              <%= f.input :box_regular %>
            </div>

            <div class="col-md-3">
              <%= f.input :mixed %>
            </div>

            <div class="col-md-3">
              <%= f.input :is_empty %>
            </div>

            <div class="col-md-3">
            </div>
          </div>
        </li>

        <li class="list-group-item">
          <div class="row text-center">

            <div class="col-md-1">
              <%= f.input :is_cc %>
            </div>

            <div class="col-md-1">
              <%= f.input :is_ep %>
            </div>

            <div class="col-md-1">
              <%= f.input :is_eco %>
            </div>
            <div class="col-md-1">
              <%= f.input :is_wine %>
            </div>
            <div class="col-md-1">
              <%= f.input :is_cava %>
            </div>
            <div class="col-md-1">
              <%= f.input :is_champagne %>
            </div>
            <div class="col-md-1">
              <%= f.input :is_shot %>
            </div>
          </div>
        </li>


        <li class="list-group-item">
          <div class="row text-center">

            <div class="col-md-2">
              <%= f.input :is_rekwup %>
            </div>

            <div class="col-md-2">
              <%= f.input :is_lln %>
            </div>

            <div class="col-md-2">
              <%= f.input :is_bep %>
            </div>
            <div class="col-md-2">
              <%= f.input :is_patro %>
            </div>
            <div class="col-md-2">
              <%= f.input :is_age %>
            </div>
          </div>
        </li>




        <li class="list-group-item">
          <div class="row text-center">

            <div class="col-md-2">
              <%= f.input :is_twenty %>
            </div>

            <div class="col-md-2">
              <%= f.input :is_twentyfive %>
            </div>
            <div class="col-md-2">
              <%= f.input :is_forty %>
            </div>

            <div class="col-md-2">
              <%= f.input :is_fifty %>
            </div>

            <div class="col-md-2">
              <%= f.input :is_litre %>
            </div>

            <div class="col-md-2">
              
            </div>

          </div>
        </li>

        <li class="list-group-item">
          <div class="row text-center">

            <div class="col-md-2">
              <%= f.input :is_kpt %>
            </div>

            <div class="col-md-2">
              <%= f.input :is_corona %>             
            </div>

            <div class="col-md-2">
              
            </div>

            <div class="col-md-2">
              
            </div>

            <div class="col-md-2">
            </div>

            <div class="col-md-2">
            </div>

          </div>
        </li>

      </ul>

          <div class="row">

            <div class="col-md-6">
              <%= link_to t("menu.back"), boxes_path, class: "btn btn-lg btn-block btn-default" %>
            </div>

            <div class="col-md-6">
              <%= f.button :submit, class: "btn btn-lg btn-block btn-info" %>
            </div>
          </div>

  <% end %>

app/views/boxes/edit.html.erb
<%= render 'form' %><br>

app/views/boxes/index.html.erb
<% if @user.admin %>

  <%= link_to t("box.new_box"), new_box_path, class: "btn btn-block btn-info" %><br>

    <ul class="list-group">

      <li class="list-group-item list-group-item-warning">
        <h4><strong>
          <%= t("box.closed_boxes") %>
        </strong></h4>
      </li>

      <li class="list-group-item">
        <div class="row">
          <strong>
            <div class="col-xs-6 col-md-2">
              <%= t("box.box_name") %>
            </div>

            <div class="col-xs-6 col-md-2">
              <%= t("offer.cups") %>
            </div>

            <div class="col-xs-6 col-md-2">
              <%= t("box.size") %>
            </div>

            <div class="col-xs-6 col-md-2">
              <%= t("article.article_type") %>
            </div>

            <div class="col-xs-6 col-md-2">
              <%= t("article.brand") %>
            </div>

            <div class="col-xs-6 col-md-2">
              <%= t("box.weight") %>
            </div>
          </strong>
        </div>              
      
      </li>


      <% @closed_boxes.each do |box| %>

        <li class="list-group-item">
          <div class="row">

              <div class="col-xs-6 col-md-2">
                <%= box.box_name %>

                  <%= link_to edit_box_path(box) do %>
                    <%= content_tag(:i, "", class: "fa fa-pencil-square-o") %>
                  <% end %>

              </div>

              <div class="col-xs-6 col-md-2">
                <%= box.cup_type %> <%= box.cup_content %>
              </div>

              <div class="col-xs-6 col-md-2">
                <%= box.size %>
              </div>

              <div class="col-xs-6 col-md-2">
                <%= box.type %>
              </div>

              <div class="col-xs-6 col-md-2">
                <%= box.cup_owner %>                
              </div>

              <div class="col-xs-6 col-md-2">
                <%= box.weight %>      
              </div>
 
          </div>                         
        </li>

      <% end %>

    </ul>


    <ul class="list-group">
      <li class="list-group-item list-group-item-warning">
        <h4><strong>
          <%= t("box.open_boxes") %>
        </strong></h4>
      </li>

      <li class="list-group-item">
        <div class="row">
          <strong>
            <div class="col-xs-6 col-md-2">
              <%= t("box.box_name") %>
            </div>

            <div class="col-xs-6 col-md-2">
              <%= t("offer.cups") %>
            </div>

            <div class="col-xs-6 col-md-2">
              <%= t("box.size") %>
            </div>

            <div class="col-xs-6 col-md-2">
              <%= t("article.article_type") %>
            </div>

            <div class="col-xs-6 col-md-2">
              <%= t("article.brand") %>
            </div>

            <div class="col-xs-6 col-md-2">
              <%= t("box.weight") %>
            </div>
          </strong>
        </div>              
      
      </li>

        <% @open_boxes.each do |box| %>


          <li class="list-group-item">
            <div class="row">

                <div class="col-xs-6 col-md-2">
                  <%= box.box_name %>

                  <%= link_to edit_box_path(box) do %>
                    <%= content_tag(:i, "", class: "fa fa-pencil-square-o") %>
                  <% end %>
                  
                </div>

                <div class="col-xs-6 col-md-2">
                  <%= box.cup_type %> <%= box.cup_content %>
                </div>

                <div class="col-xs-6 col-md-2">
                  <%= box.size %>
                </div>

                <div class="col-xs-6 col-md-2">
                  <%= box.type %>
                </div>

                <div class="col-xs-6 col-md-2">
                  <%= box.cup_owner %>                
                </div>

                <div class="col-xs-6 col-md-2">
                  <%= box.weight %>      
                </div>
   
            </div>                         
          </li>

        <% end %>

      </ul>

  <% end %>

app/views/boxes/new.html.erb
<%= render 'form' %><br>

app/views/boxes/show.html.erb
  <ul class="list-group">
    <li class="list-group-item list-group-item-warning">
      <div class="row">
        <strong>
        <div class="col-md-4">
          
            <%= @box.id %> - <%= @box.box_name %>

              <%= link_to edit_box_path(@box) do %>
                <span class="glyphicon glyphicon-pencil btn btn-default btn-xs" aria-hidden="true"></span>
              <% end %>
            
        </div>

        <div class="col-md-4">
          <% if @box.box_regular %>
            
            <%= t("box.box_regular") %>

          <% end %>
        </div>

        <div class="col-md-4">

          <% if @box.mixed %>

            <%= t("box.mixed") %>
              
          <% end %>
        </div>
        </strong>
      </div>      
    </li>
        
    <li class="list-group-item">
      <div class="row">
        <strong>
          <div class="col-md-2">

            <% if @box.is_empty %>

              <%= t("box.is_empty") %>
                
            <% end %>
          </div>

          <div class="col-md-2">

            <% if @box.bigbox %>

              <%= t("box.bigbox") %>
                
            <% end %>
          </div>

          <div class="col-md-2">

            <% if @box.smallbox %>

              <%= t("box.smallbox") %>
                
            <% end %>
          </div>
        

          <div class="col-md-2 text-center">

              <%= t("box.weight") %>
            <br>
              <%= @box.weight %> kg
          </div>
        </strong>
          <% if current_user.admin %>

            <% if @box.box_is_full %>

              <div class="col-md-2 text-center">
                <strong>
                <%= t("box.box_is_full") %>
                </strong>
              </div>

              <div class="col-md-2">
                <%= simple_form_for(@box) do |f| %>
                  <%= f.error_notification %>
                  <%= f.hidden_field :box_is_full, :value => false %>
                  <%= f.submit t("box.open_box"), class: "btn btn-success" %>
                <% end %>
              </div>

            <% else %>

              <div class="col-md-2 text-center">
                <strong>
                  <%= t("box.box_is_not_full") %>
                </strong>
              </div>

              <div class="col-md-2">
                <%= simple_form_for(@box) do |f| %>
                  <%= f.error_notification %>
                    <%= f.hidden_field :box_is_full, :value => true %>
                    <%= f.submit t("box.close_box"), class: "btn btn-success" %>
                <% end %>
              </div> 

            <% end %>
          <% end %>
        </div>
    </li>

    <li class="list-group-item">
      <div class="row">
        <strong>
          <div class="col-md-1">

            <% if @box.is_cc %>

              <%= t("article.is_cc") %>
                
            <% end %>
          </div>

          <div class="col-md-1">

            <% if @box.is_ep %>

              <%= t("article.is_ep") %>
                
            <% end %>
          </div>

          <div class="col-md-1">

            <% if @box.is_eco %>

              <%= t("article.is_eco") %>
                
            <% end %>
          </div>

          <div class="col-md-1">

            <% if @box.is_wine %>

              <%= t("article.is_wine") %>
                
            <% end %>
          </div>

          <div class="col-md-1">

            <% if @box.is_cava %>

              <%= t("article.is_cava") %>
                
            <% end %>
          </div>

          <div class="col-md-1">

            <% if @box.is_champagne %>

              <%= t("article.is_champagne") %>
                
            <% end %>
          </div>

          <div class="col-md-1">

            <% if @box.is_shot %>

              <%= t("article.is_shot") %>
                
            <% end %>
          </div>
        </strong>
      </div>
    </li>

    <li class="list-group-item">
      <div class="row">
        <strong>
          <div class="col-md-2">

            <% if @box.is_twenty %>

              <%= t("article.is_twenty") %>
                
            <% end %>
          </div>

          <div class="col-md-2">

            <% if @box.is_twentyfive %>

              <%= t("article.is_twentyfive") %>
                
            <% end %>
          </div>

          <div class="col-md-2">

            <% if @box.is_forty %>

              <%= t("article.is_forty") %>
                
            <% end %>
          </div>

          <div class="col-md-2">

            <% if @box.is_fifty %>

              <%= t("article.is_fifty") %>
                
            <% end %>
          </div>

          <div class="col-md-2">
            <% if @box.is_litre %>

              <%= t("article.is_litre") %>
                
            <% end %>
          </div>

          <div class="col-md-2">


          </div>
        </strong>
      </div>
    </li>
    
    <li class="list-group-item">
      <div class="row">
        <strong>
          <div class="col-md-2">

            <% if @box.is_rekwup %>

              <%= t("article.rekwup_cup") %>
                
            <% end %>
          </div>

          <div class="col-md-2">

            <% if @box.is_lln %>

              <%= t("article.is_lln") %>
                
            <% end %>
          </div>

          <div class="col-md-2">

            <% if @box.is_bep %>

              <%= t("article.is_bep") %>
                
            <% end %>
          </div>

          <div class="col-md-2">

            <% if @box.is_patro %>

              <%= t("article.is_patro") %>
                
            <% end %>
          </div>

          <div class="col-md-2">
            <% if @box.is_age %>

              <%= t("article.is_age") %>
                
            <% end %>
          </div>

          <div class="col-md-2">


          </div>
        </strong>
      </div>
    </li>



    <li class="list-group-item">
      <div class="row">
        <strong>
          <div class="col-md-2">

            <% if @box.is_kpt %>

              <%= t("box.is_kpt") %>
                
            <% end %>
          </div>

          <div class="col-md-2">

            <% if @box.is_corona %>

              <%= t("box.is_corona") %>
                
            <% end %>
          </div>

          <div class="col-md-2">


          </div>

          <div class="col-md-2">

          </div>

          <div class="col-md-2">

          </div>

          <div class="col-md-2">


          </div>
        </strong>
      </div>
    </li>

    <li class="list-group-item list-group-item-warning">
      <div class="row">

        <div class="col-md-4">
          <strong><%= t("article.selected_articles") %></strong>
        </div>

        <div class="col-md-4">
          <strong><%= t("article.quantity") %></strong>
        </div>

        <div class="col-md-4">
          
        </div>

      </div>
    </li>
  
    <li class="list-group-item">


        <% @thisboxdetails.each do |thisboxdetail| %>
          <div class="row">
            <div class="col-md-4">
              <%= thisboxdetail.article.full_name if thisboxdetail.article %>

              <% unless @box.box_is_full %>
                <%= link_to edit_boxdetail_path(thisboxdetail) do %>
                  <span class="glyphicon glyphicon-pencil btn btn-default btn-xs" aria-hidden="true"></span>
                <% end %>
              <% end %>
            </div>

            <div class="col-md-4">
              <%= thisboxdetail.box_article_quantity if thisboxdetail.box_article_quantity %>


            </div>
         
            <div class="col-md-4">
              <%= link_to thisboxdetail, method: :delete, data: { confirm: 'Are you sure?' } do %>
                <%= content_tag(:i, "", class: "fa fa-times btn btn-default") %>
              <% end %> 
            </div>
          </div>      
        <% end %>  

    </li>


    <% if @box.box_is_full %>

    <% else %>

      <li class="list-group-item list-group-item-warning">
        <strong><%= t("box.add_article") %></strong>
      </li>

      <li class="list-group-item">
        <div class="row">

          <%= simple_form_for(@new_boxdetail) do |f| %>
            <%= f.error_notification %>

            	<%= f.hidden_field :box_id, :value => @box.id %>

               <div class="col-md-4">
                <%= f.label :article_id %>
                <%= f.collection_select :article_id, Article.all.order('article_name ASC'), :id, :full_name, {prompt: false}, {class: "form-control styled-select"} %>
              </div>

              <div class="col-md-4">
                <%= f.input :box_article_quantity %>
              </div>

              <div class="col-md-4">
                <br>
                <%= f.button :submit, class: "btn btn-success" %>
              </div>

          <% end %>

        </div>
      </li>
    <% end %>
  </ul>


    <div class="row">

      <div class="col-md-6">
        
      </div>
      <div class="col-md-6">
        <%= link_to t("menu.back"), boxes_path, class: "btn btn-lg btn-block btn-default" %>
      </div>
    </div>