config/routes.rb
Rails.application.routes.draw do
  get 'reporting/attendances'

  get 'reporting/statistics'
  get 'reporting/interim'
  get 'reporting/interim_pdf'
  get 'reporting/invoices'

  resources :attendances
  resources :energies
  get 'lln_imports/index'

  get 'lln_imports/import'

  resources :invoices do
    member do
      get 'show_detail'
      get 'show_surfaces'
      get 'show_surfaces_bis'
      get 'lln_detail_bis'
      get 'lln_detail_ter'
      get 'lln_detail_quater'
    end
  end
  resources :prices
  resources :parcels
  resources :sorting_details
  resources :sortings
  resources :washes
  resources :return_details
  resources :return_boxes
  resources :deliveries
  resources :offer_articles
  resources :offer_boxes
  resources :offers
  resources :negociated_prices
  resources :boxdetails
  resources :boxes
  resources :articles
  resources :events
  root to: 'visitors#index'
  devise_for :users
  resources :users

  resources :lln_imports do
    collection {post :import}
  end

  
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /offers
  # GET /offers.json
  def index
    @offers = Offer.all.order('id ASC')
    @events = Event.all
    @user = current_user

    @confirmedoffers = Offer.where(:client_confirmation => true)
    @rejectedoffers = Offer.where(:client_confirmation => false)
    @pendingoffers = Offer.where(:client_confirmation => nil)
    @confirmed_not_paid = @confirmedoffers.where(:confirmation_invoice => nil)
    @confirmed_paid = @confirmedoffers.where(:confirmation_invoice => true)
    @confirmed_not_sent = @confirmed_paid.where(:admin_confirmation => nil)
    @confirmed = @confirmedoffers.where(:admin_confirmation => true)

    @myoffers = Offer.where(:organizer => current_user)
    @myconfirmedoffers = @myoffers.where(:client_confirmation => true)
    @myrejectedoffers = @myoffers.where(:client_confirmation => false)
    @mypendingoffers = @myoffers.where(:client_confirmation => nil)

    @new_delivery = Delivery.new

  end

  # GET /offers/1
  # GET /offers/1.json
  def show
    @offer = Offer.find(params[:id])
    @user = current_user
    @event = @offer.event
    @organizer = @offer.organizer
    @confirmation = @offer.client_confirmation
    @confirmation_invoice = @offer.confirmation_invoice

    @articles = Article.all

    @new_offer_box = OfferBox.new
    @offer_boxes = OfferBox.all
    @thisofferboxes = @offer_boxes.where(:offer_id => @offer.id)
    
    @new_offer_article = OfferArticle.new
    @offer_articles = OfferArticle.all
    @thisofferarticles = @offer_articles.where(:offer_id => @offer.id)

    @prices = Price.all
    @regular_prices = @prices.where(:regular => true)
    @new_delivery = Delivery.new

    @new_return_box = ReturnBox.new

    @admin = @user.admin
    unless @admin or @organizer
      redirect_to :root, :alert => t("notice.access")
    end
  end

  # GET /offers/new
  def new
    @offer = Offer.new
    @user =current_user
    @admin = @user.admin
    unless @admin
      redirect_to :root, :alert => t("notice.access")
    end
  end

  # GET /offers/1/edit
  def edit
    @offer = Offer.find(params[:id])
    @user = current_user
    @organizer = @offer.organizer
    @event = @offer.event
    @admin = @user.admin
    @staff = @user.staff
    unless @admin or @organizer or @staff
      redirect_to :root, :alert => t("notice.access")
    end
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(offer_params)
    @user =current_user
    @admin = @user.admin
    @staff = @user.staff


    respond_to do |format|
      if @offer.save
        @offer.automatic

        if @offer.lln_daily && !@offer.unforeseen_return
          LlnImport.where(:id => @offer.organizer.lln_id).each do |import|

            if import.return_box >= 1
              ReturnBox.create(:offer_id => @offer.id, :return_date => Date.today + 1.day)
              @return_box = ReturnBox.last
              ReturnDetail.create(:return_box_id => @return_box.id, :box_id => Box.is_lln.is_twentyfive.first.id, :dirty => import.return_box)
            end
            if import.total_delivery >= 1
              Delivery.create(:offer_id => @offer.id, :delivery_date => Date.today + 1.day, :return_date => Date.today + 1.day)

              if import.lln_twentyfive >= 1
                OfferBox.create(:offer_id => @offer.id, :box_id => Box.is_lln.is_twentyfive.first.id, :quantity => import.lln_twentyfive)
              end

              if import.lln_fifty >= 1
                OfferBox.create(:offer_id => @offer.id, :box_id => Box.is_lln.is_fifty.first.id, :quantity => import.lln_fifty)
              end

              if import.lln_litre >= 1
                OfferBox.create(:offer_id => @offer.id, :box_id => Box.is_lln.is_litre.first.id, :quantity => import.lln_litre)
              end

              if import.empty_box >= 1
                OfferBox.create(:offer_id => @offer.id, :box_id => Box.is_empty.first.id, :quantity => import.empty_box)
              end

              if import.kpt_box >= 1
                OfferBox.create(:offer_id => @offer.id, :box_id => Box.is_lln.is_twentyfive.is_kpt.first.id, :quantity => import.kpt_box)
              end
            end

          end
        end

        if @offer.unforeseen_return
          ReturnBox.create(:offer_id => @offer.id, :return_date => Date.today)
          @return_box = ReturnBox.last
        end
        
          format.html { redirect_to :back, notice: 'Offer was successfully created.' }
          format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :new }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    @offer = Offer.find(params[:id])
    @user = @offer.organizer
           
    respond_to do |format|
      if @offer.update(offer_params)
        if @offer.send_email
          UserMailer.offer_email(@user, @offer).deliver_later
          @offer.update_attributes(:send_email => false)
        end
        if @offer.confirmation_invoice
          Invoice.create(:offer_id => @offer.id, :client_id => @offer.organizer.id, :doc_invoice => true, :confirmation => true)
          @invoice = Invoice.last
          @invoice.update_attributes(:doc_number => @invoice.invoice_number, :total_htva => @invoice.total_htva_deposit, :total_tva => @invoice.total_tva_deposit, :total_tvac => @invoice.total_tvac_deposit)
        end
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.offer_boxes.each do |offer_box|
      offer_box.destroy
    end
    @offer.offer_articles.each do |offer_article|
      offer_article.destroy
    end
    @offer.return_boxes.each do |return_box|
      return_box.destroy
    end
    @offer.delivery.destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url, notice: 'Offer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_params
      params.require(:offer).permit(:event_id, :organizer_id, :client_confirmation, :admin_confirmation, :send_email, :lln_daily, :unforeseen_return, :lln_invoice, :confirmation_invoice, :comment)
    end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_add_article.html.erb
        <ul class="list-group">
          <li class="list-group-item list-group-item-warning">
            <h5><strong><%= t("offer.add_article")%></strong></h5>
          </li>

          <li class="list-group-item">
            <div class="row">
            <%= simple_form_for(@new_offer_article) do |f| %>
              <%= f.error_notification %>

              
            	<%= f.hidden_field :offer_id, :value => @offer.id %>
               <div class="col-xs-12 col-md-4">
                <%= f.label :article_id %>
                <%= f.collection_select :article_id, Article.not_washable.order('article_name ASC'), :id, :full_name, {prompt: false}, {class: "form-control styled-select"} %>


              </div>
              <div class="col-xs-12 col-md-4">
                <%= f.input :quantity %>
              </div>

              <div class="col-xs-12 col-md-4">
                <br><%= f.button :submit, class: "btn btn-success" %>
              </div>

            <% end %>
            </div>
          </li>



        </ul>

app/views/offers/_article_detail.html.erb
					<ul class="list-group">
					  <li class="list-group-item">
					    <div class="row text-center">
					      <strong>

					        <div class="col-xs-4 col-md-4">
					          <%= t("offer_article.article_name") %>
					        </div>

					        <div class="col-xs-4 col-md-4">
					            <%= t("offer_article.quantity") %>  
					        </div>

					        <div class="col-xs-4 col-md-4">
					            <%= t("article.sell_price") %>
					        </div>
					      
					    	</strong>
					    </div>
					  </li>
					

        <% @thisofferarticles.each do |thisofferarticle| %>

					
					  <li class="list-group-item">
					    <div class="row text-center">

					    	<div class="col-xs-4 col-md-4">
						      <%= thisofferarticle.article.article_name if thisofferarticle.article %>
						          
						          <% if current_user.admin %>
												<%= link_to edit_offer_article_path(thisofferarticle) do %>
											     <%= content_tag(:i, "", class: "fa fa-pencil-square-o btn btn-xs btn-default pull-right") %> 
											  <% end %>

			                	<%= link_to thisofferarticle, method: :delete, data: { confirm: 'Are you sure?' } do %>
											  	<%= content_tag(:i, "", class: "fa fa-times btn btn-xs btn-default pull-right") %>
											  <% end %>
											 <% end %>

					    	</div>

					      <div class="col-xs-4 col-md-4">
					        <%= thisofferarticle.quantity if thisofferarticle.quantity %>
					      </div>

					      <div class="col-xs-4 col-md-4">
					      	<% if thisofferarticle.article.transport %>
					          <%= number_to_currency(@offer.transport_price,:unit =>'€', :precision => 4) %>
					        <% else %>
					        	<%= number_to_currency(@regular_prices.where(:article_id => thisofferarticle.article.id).last.sell,:unit =>'€', :precision => 2) if @regular_prices.where(:article_id => thisofferarticle.article.id).any? %>
					        <% end %>
					      </div>

					    
					    </div>
					  </li>		  
					<% end %>
      	</ul>

	<% if current_user == @organizer %>

    <div class="row">

      <div class="col-xs-6 col-md-6">
        <%= link_to t("menu.back"), events_path, class: "btn btn-lg btn-block btn-default" %>
      </div>
      <div class="col-xs-6 col-md-6">
        <%= link_to t("offer.yours"), offers_path, class: "btn btn-lg btn-block btn-info" %>
      </div>
    </div>
	
	<% end %>

app/views/offers/_box_detail.html.erb
					<ul class="list-group">

						<li class="list-group-item">
        			<h4><%= t("offer.proposal") %></h4>
      			</li>

					  <li class="list-group-item">
					    <div class="row text-center">
					      <strong>
			          
				          <div class="col-xs-6 col-md-4">
						        <%= t("offer_box.box_name") %>
						      </div>

						      <div class="col-xs-3 col-md-4 text-center">
						        <%= t("offer_box.quantity") %>     
						      </div>

								<div class="col-xs-3 col-md-4 text-center">
						       <%= t("article.washing_price") %>     
						    </div>

					    </strong>
					    </div>
					  </li>
					
        	<% @thisofferboxes.each do |thisofferbox| %>

					
			      <li class="list-group-item list-group-item-info">
			        <div class="row">			          
			          <div class="col-xs-6 col-md-4">
			            <% if thisofferbox.box %>

			            	<% if thisofferbox.box.is_empty %>
			            		<%= thisofferbox.box.box_name %>
			            	<% else %>

			                <%= thisofferbox.box.box_name %> (<%= thisofferbox.box.boxdetails.last.box_article_quantity %> <%= thisofferbox.box.boxdetails.last.article.full_name %>)
			              <% end %>

	                	<% if current_user.admin %>
											<%= link_to edit_offer_box_path(thisofferbox) do %>
										     <%= content_tag(:i, "", class: "fa fa-pencil-square-o btn btn-xs btn-default pull-right") %> 
										  <% end %>

		                	<%= link_to thisofferbox, method: :delete, data: { confirm: 'Are you sure?' } do %>
										  	<%= content_tag(:i, "", class: "fa fa-times btn btn-xs btn-default pull-right") %>
										  <% end %> 
										<% end %>
			  
			            <% end %>
			          </div>

			          <div class="col-xs-3 col-md-4 text-center">

			          	<% if thisofferbox.box.is_empty %>

			          		<%= thisofferbox.quantity if thisofferbox.quantity %> <%= t("offer.boxes") %>

			          	<% else %>

			              <%= thisofferbox.quantity if thisofferbox.quantity %> <%= t("offer.boxes") %> - 
			        			<%= thisofferbox.quantity * thisofferbox.box.boxdetails.last.box_article_quantity %> <%= t("offer.cups") %>

			            <% end %>
			          </div>

			         	<div class="col-xs-3 col-md-4 text-center">

			         		<% if thisofferbox.box.is_big_box %>

			         			<% if @offer.event.is_bep %>

					          	<%= number_to_currency(thisofferbox.box.boxdetails.last.article.right_wash_price(User.is_bep.first), :unit => "€", :precision => 3) %>

					          <% else %>

					          	<%= number_to_currency(thisofferbox.box.boxdetails.last.article.right_wash_price(@offer.organizer), :unit => "€", :precision => 3) %>

					          <% end %>
					        <% end %>

					        <% if thisofferbox.box.is_small_box %>

			         			<% if @offer.event.is_bep %>

					          	<%= number_to_currency(thisofferbox.box.boxdetails.last.article.right_washing_small_price(User.is_bep.first), :unit => "€", :precision => 3) %>

					          <% else %>

					         	<%= number_to_currency(thisofferbox.box.boxdetails.last.article.right_washing_small_price(@offer.organizer), :unit => "€", :precision => 3) %>
					         	
					          <% end %>
					        <% end %>
			        	</div>
			        </div>
			      </li>

			      <li class="list-group-item">
			        <div class="row">

			        	<div class="col-xs-6 col-md-3">
			          
									<strong>Suppléments</strong>

				        </div>

			        	<div class="col-xs-6 col-md-3 text-center">
			          	<strong><%= t("article.handwash_price") %></strong><br>
			         			<% if @offer.event.is_bep %>
					          	<%= number_to_currency(thisofferbox.box.boxdetails.last.article.right_handwash_price(User.is_bep.first), :unit => "€", :precision => 3) %>
					          <% else %>
											<%= number_to_currency(thisofferbox.box.boxdetails.last.article.right_handwash_price(@offer.organizer), :unit => "€", :precision => 3) %>
										<% end %>
				        </div>

			         	<div class="col-xs-6 col-md-3 text-center">						       
						      <strong><%= t("article.tab_price") %></strong><br>
			         			<% if @offer.event.is_bep %>
					          	<%= number_to_currency(thisofferbox.box.boxdetails.last.article.right_handling_price(User.is_bep.first), :unit => "€", :precision => 3) %>
					          <% else %>						      
				          		<%= number_to_currency(thisofferbox.box.boxdetails.last.article.right_handling_price(@offer.organizer), :unit => "€", :precision => 3) %>
				          	<% end %>
			        	</div>

			         	<div class="col-xs-6 col-md-3 text-center">
						      <strong><%= t("article.deposit_price") %></strong><br>
			         			<% if @offer.event.is_bep %>
					          	<%= number_to_currency(thisofferbox.box.boxdetails.last.article.right_deposit_price(User.is_bep.first, @offer.event), :unit => "€", :precision => 3) %>
					          <% else %>	
				          		<%= number_to_currency(thisofferbox.box.boxdetails.last.article.right_deposit_price(@offer.organizer, @offer.event), :unit => "€", :precision => 3) %>
				          	<% end %>

			        	</div>

			        </div>
			      </li>

					<% end %>
				</ul>

app/views/offers/_event_info.html.erb
<ul class="list-group">
  <li class="list-group-item list-group-item-success">



      <div class="col-md-6">
        <h4><%= t("offer.reference")%><%= @offer.created_at.strftime("%Y") %> - <%= @offer.id %>

          <% if @offer.client_confirmation = true %>
            - <%= t("offer.client_confirmed") %></h4>
          <% end %>

      </div>

      <div class="col-md-2">

        <% if @offer.client_confirmation = true %>

            <% if @organizer = @user %>

                    <%= simple_form_for(@offer) do |f| %>
                      <%= f.error_notification %>

                        <%= f.hidden_field :client_confirmation, :value => false %>             
                        <%= f.submit t("menu.cancel"), class: "btn btn-xs btn-default" %>

                    <% end %>
            <% end %>

        <% else %>

            <%= simple_form_for(@offer) do |f| %>
              <%= f.error_notification %>       

                <%= f.hidden_field :client_confirmation, :value => true %>             
                <%= f.submit t("offer.confirm"), class: "btn btn-info pull-right" %>

            <% end %>
      </div>
          <% end %>

      <div class="col-md-4">
        <% if current_user.admin %>
          <% if @offer.client_confirmation? %>

            <%= simple_form_for(@offer) do |f| %>
              <%= f.error_notification %>           
                <%= f.hidden_field :admin_confirmation, :value => true %>

              <div class="form-actions">
                <%= f.submit t("offer.delivery"), class: "btn btn-success" %>
              </div>

            <% end %>
          <% end %>
        <% end %>
      </div>
  
  </li>

  <li class="list-group-item"><strong><%= @event.event_name %></strong>
    <%= link_to edit_event_path(@event) do %>
      <%= content_tag(:i, "", class: "fa fa-pencil") %> 
    <% end %>
  </li>

  <li class="list-group-item">
    <strong><%= t("event.organizer_name") %> </strong><%= @organizer.full_name if @organizer %>
  </li>

  <li class="list-group-item">
    <div class="row text-center">

      <div class="col-md-4">
        <strong><%= t("event.expected_pax") %></strong><br><br><%= @event.expected_pax %>
      </div>

      <div class="col-md-4">
        <strong><%= t("event.last_pax") %></strong><br><%= @event.last_pax %>      
      </div>

      <div class="col-md-4">
        <strong><%= t("event.last_consumption") %></strong><br><%= @event.last_consumption %>   
      </div>

    </div>
  </li>
    
  <li class="list-group-item"><strong><%= t("event.comment") %></strong><br><%= @event.comment %></li>

</ul>

app/views/offers/_event_info_client.html.erb
<% if @user.offers.where(:client_confirmation => true).any? %>

  <% if @user.address.blank? %>

    <ul class="list-group">
      <li class="list-group-item list-group-item-warning">
        <h4><%= t("offer.complete_profile") %></h4>
      </li>
    </ul>

      <%= link_to t("user.fill_profile"), edit_user_path(@user), class: "btn btn-lg btn-block btn-info" %>

      <br>
  <% end %>

<% end %>



<ul class="list-group">
  <li class="list-group-item list-group-item-success">
    <div class="row">

      <div class="col-xs-12 col-md-6">
        <h4><%= t("offer.reference")%><%= @offer.created_at.strftime("%Y") %> - <%= @offer.id %>

          <% if @confirmation %>
            - <%= t("offer.you_confirmed") %>
          <% end %></h4>

      </div>

      <div class="col-xs-12 col-md-2">


        <% unless @confirmation %>

            <%= simple_form_for(@offer) do |f| %>
              <%= f.error_notification %>       

                <%= f.hidden_field :client_confirmation, :value => true %>             
                <%= f.submit t("offer.confirm"), class: "btn btn-info pull-right" %>

            <% end %>
        <% end %>

      </div>
          

      <div class="col-xs-12 col-md-4">

          <% if @confirmation && @offer.admin_confirmation == nil %>

            <% if @offer.sent_at.present? %>

              <% if Date.today >= @offer.sent_at + 16.days or Date.today <= @offer.event.event_start_date - 5.days %>

                <%= simple_form_for(@offer) do |f| %>
                  <%= f.error_notification %>       

                    <%= f.hidden_field :client_confirmation, :value => false %>             
                    <%= f.submit t("offer.cancel"), class: "btn btn-warning pull-right" %>

                <% end %>
              <% end %>

            <% else %>

              <% if Date.today >= @offer.created_at + 16.days or Date.today <= @offer.event.event_start_date - 5.days %>

                <%= simple_form_for(@offer) do |f| %>
                  <%= f.error_notification %>       

                    <%= f.hidden_field :client_confirmation, :value => false %>             
                    <%= f.submit t("offer.cancel"), class: "btn btn-warning pull-right" %>

                <% end %>
              <% end %>

            <% end %>
          <% end %>
      </div>
    </div>
  </li>

  <li class="list-group-item list-group-item-warning"><strong>
    <%= t("event.confirmation_warning") %><br>
    <%= t("event.confirmation_question") %>
  </strong></li>

  <li class="list-group-item"><strong><%= @event.event_name %></strong>

    <%= link_to t("event.edit_yours"), edit_event_path(@event), class: "btn btn-default" %>

  </li>

  <li class="list-group-item">
    <strong><%= t("event.organizer_name") %> </strong><%= @organizer.full_name if @organizer %>
  </li>

  <li class="list-group-item">
    <div class="row text-center">

      <div class="col-xs-12 col-md-4">
        <strong><%= t("event.expected_pax") %></strong><br><br><%= @event.expected_pax %>
      </div>

      <div class="col-xs-12 col-md-4">
        <strong><%= t("event.last_pax") %></strong><br><%= @event.last_pax %>      
      </div>

      <div class="col-xs-12 col-md-4">
        <strong><%= t("event.last_consumption") %></strong><br><%= @event.last_consumption %>   
      </div>

    </div>
  </li>
    
  <li class="list-group-item"><strong><%= t("event.comment") %></strong><br><%= @event.comment %></li>

</ul>

app/views/offers/_index_client.html.erb
<% if @user.offers.where(:client_confirmation => true).any? %>

  <% if @user.address.blank? %>

    <ul class="list-group">
      <li class="list-group-item list-group-item-warning">
        <h4><%= t("offer.complete_profile") %></h4>
      </li>
    </ul>

      <%= link_to t("user.fill_profile"), edit_user_path(@user), class: "btn btn-lg btn-block btn-info" %>

      <br>
  <% end %>

<% end %>


<ul class="list-group">

	<li class="list-group-item list-group-item-warning">
		<h4><%= t("offer.waiting") %></h4>
	</li>

		<% @mypendingoffers.each do |offer| %>
													
  		<% if offer.event.address.present? %>

				<li class="list-group-item">
					<div class="row">

						<div class="col-xs-6 col-md-6">			
							<strong>
								<%= t("offer.reference")%><%= offer.created_at.strftime("%Y") %> - <%= offer.id %>
								<br>
								<%= offer.event.event_name %>
							</strong>
						</div>

						<div class="col-xs-2 col-md-2">

								<%= link_to offer_path(offer) do %>
									<%= content_tag(:i, "", class: "fa fa-info fa-2x") %> 
								<% end %>
    		    </div>

						<div class="col-xs-4 col-md-4">

							<%= simple_form_for(offer) do |f| %>
	    					<%= f.error_notification %>				

									<%= f.hidden_field :client_confirmation, :value => true %>			       
				      		<%= f.submit t("offer.confirm"), class: "btn btn-info" %>

      				<% end %> <!-- offer form -->
    		    </div>
			    </div>
				</li>

  		<% else %> <!-- address present -->

			    <li class="list-group-item list-group-item-success">
						<strong><%= t("event.please_complete") %></strong>
					</li>

        		<%= simple_form_for(offer.event) do |f| %>
    					<%= f.error_notification %>

		    			<li class="list-group-item">
		    				<strong>
										<%= t("offer.reference")%><%= offer.created_at.strftime("%Y") %> - <%= offer.id %>
										<br>
										<%= offer.event.event_name %>
									</strong>
							</li>

							<li class="list-group-item">

		    				<div class="row">

		    					<div class="col-xs-12 col-md-5">			
										<%= f.input :address %>
									</div>

									<div class="col-xs-6 col-md-2">
										<%= f.input :post_code %>
									</div>

									<div class="col-xs-6 col-md-3">
										<%= f.input :city %>
									</div>

									<div class="col-xs-12 col-md-2">
										<%= f.input :country %>
									</div>

								</div>
							</li>

							<li class="list-group-item">
								<div class="row">

									<div class="col-xs-12 col-md-6">
										<%= f.input :delivery_date %>
									</div>

										<div class="col-xs-12 col-md-6">
										<%= f.input :return_date %>
									</div>

								</div>
							</li>

							<li class="list-group-item">

								<div class="row">
									<div class="col-xs-12 col-md-6">
										<%= f.input :contact %>
									</div>

									<div class="col-xs-12 col-md-6">
										<%= f.input :phone %>
									</div>

										<%= f.hidden_field :is_complete, :value => true %>
			        	</div>

			        </li>

	        		<li class="list-group-item">
	        			<div class="row">

	        			<%= f.submit t("event.complete"), class: "btn btn-info pull-right" %>
	       
	        		<% end %> <!-- event form -->

					      	<%= simple_form_for(offer) do |f| %>
			    					<%= f.error_notification %>				

											<%= f.hidden_field :client_confirmation, :value => false %>			       
						      		<%= f.submit t("offer.reject"), class: "btn btn-default pull-left" %>
						      <% end %>
						    </div>
			    		</li>
					    		
    				 

		<% end %>  <!-- pending offers -->
		
		<% end %>	<!-- my pending offers do -->	
</ul>          	

<ul class="list-group">
				<li class="list-group-item list-group-item-warning">
					<h4><%= t("offer.your_confirmed") %></h4>
				</li>

				<% @myconfirmedoffers.each do |offer| %>

					<li class="list-group-item">
						<div class="row">

							<div class="col-xs-6 col-md-6">
								<strong>
									<%= t("offer.reference")%><%= offer.created_at.strftime("%Y") %> - <%= offer.id %>
								<br>
									<%= offer.event.event_name %>
								</strong>
							</div>

						<div class="col-xs-2 col-md-2">

								<%= link_to offer_path(offer) do %>
									<%= content_tag(:i, "", class: "fa fa-info fa-2x") %> 
								<% end %>
    		    </div>

							<div class="col-xs-4 col-md-4">
								

      		    </div>

				    </div>
					</li>
				<% end %>

				<li class="list-group-item list-group-item-warning">
					<h4><%= t("offer.your_rejected") %></h4>
				</li>

				<% @myrejectedoffers.each do |offer| %>

					<li class="list-group-item">
						<div class="row">

							<div class="col-xs-6 col-md-6">
								<strong>
									<%= t("offer.reference")%><%= offer.created_at.strftime("%Y") %> - <%= offer.id %>
								<br>
									<%= offer.event.event_name %>
								</strong>
							</div>

						<div class="col-xs-2 col-md-2">

								<%= link_to offer_path(offer) do %>
									<%= content_tag(:i, "", class: "fa fa-info fa-2x") %> 
								<% end %>
    		    </div>

      		    <div class="col-xs-4 col-md-4">
								
							<%= simple_form_for(offer) do |f| %>
	    					<%= f.error_notification %>				

									<%= f.hidden_field :client_confirmation, :value => true %>			       
				      		<%= f.submit t("offer.confirm"), class: "btn btn-info" %>
				      <% end %>

      		    </div>

				    </div>
					</li>
				<% end %>	
</ul>	<!-- list-group -->











			